### PR TITLE
Adapt to clang 9

### PR DESCRIPTION
**Pull request by davidrohr**
@sawenzel : Not to be merged now, but when we move to clang 8, these are the required changes.

### CODE REVIEW

**Comment by sawenzel** [comment]
Thanks a lot. Do you also have a bumped version of the clang recipe/repository?

**Comment by davidrohr** [comment]
No, sorry, I am using my system clang installation.
Kind Regards
David Rohr

Sent from my mobile. (Excuse the typos!)

On April 29, 2019 9:06:21 AM GMT+02:00, Sandro Wenzel <notifications@github.com> wrote:
>Thanks a lot. Do you also have a bumped version of the clang
>recipe/repository?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AliceO2Group/O2CodeChecker/pull/30#issuecomment-487471564

Kind Regards
David Rohr

Sent from my mobile. (Excuse the typos!)

**Comment by davidrohr** [comment]
@sawenzel : Is there a plan to move to clang 8? Are you working on a clang 8 recipe? Or should I have a look?

**Comment by sawenzel** [comment]
Yes. In principle a student wanted to migrate to clang-8 (mainly update of the repo). I'll come back to you when I have more news.

**Comment by anerokhi** [comment]
https://github.com/alisw/clang/pull/3

**Comment by davidrohr** [comment]
@sawenzel @anerokhi : Since clang 9 is out now, should we bump directly to clang 9? I could give it a try if the code checker works with clang 9 if you agree.

**Comment by davidrohr** [comment]
Built locally with clang 9, and the code checker works correctly

**Pull request merged**
